name: Close Ended Lots

on:
  schedule:
    - cron: "*/10 * * * *"   # هر ۱۰ دقیقه
  workflow_dispatch:         # اجرای دستی از تب Actions

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call cron endpoint
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          CRON_TOKEN: ${{ secrets.CRON_TOKEN }}
        run: |
          set -e
          echo "Hitting $BASE_URL/api/cron/close-ended"
          code=$(curl -sS -o /tmp/resp.txt -w "%{http_code}" "$BASE_URL/api/cron/close-ended?token=$CRON_TOKEN")
          echo "HTTP $code"
          echo "Body:"
          cat /tmp/resp.txt
          test "$code" -ge 200 -a "$code" -lt 400
